#!/usr/bin/env python3

'''
    genetribe
    Copyright (C) Yongming Chen
    Contact: chen_yongming@126.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
'''

import sys
import subprocess
import os

def PrintVersion() :
	print ("Version: 1.0.0 (2020)")

argv_len = len(sys.argv)

DIR=os.path.dirname(sys.argv[0])

if (argv_len) == 1  or sys.argv[1] in ["-h", "-H", "--help"]:
	print ("")
	print ("Program: genetribe (tool for homolog inference)")
	PrintVersion()
	print ("")
	print ("Usage: genetribe <command> [options]")
	print ("")
	print ("Subcommands include:")
	print ("")
	print ("[ pipeline ]")
	print ("     core           Core workflow of genetribe")
	print ("     corenog        Workflow not grouping chromosomes")
	print ("     sameassembly   Homolog inference for same assembly")
	print ("")
	print ("[ tools ]")
	print ("     RBH            Obtain Reciprocal Best Hits (RBH)")
	print ("     CBS            Calculate Collinearity Block Score (CBS)")
	print ("     longestcds     Extract longest protein sequence from protein fasta")
	print ("")
	print ("Author: Chen,Yongming; chen_yongming@126.com")
	print ("")
else:
	if argv_len == 2 or sys.argv[2] in ["-h", "-H", "--help"]:
		command = ["-h"]
	else:
		command = sys.argv[2:]
	code = sys.argv[1]
	if code == "core":
		subprocess.call([DIR + "/bin/core"]+ command)
	elif code == "corenog":
		subprocess.call([DIR + "/bin/corenog"]+ command)
	elif code == "sameassembly":
		subprocess.call([DIR + "/bin/sameassembly"]+ command)
	elif code == "RBH":
		subprocess.call([DIR + "/bin/RBH"]+ command)
	elif code == "longestcds":
		subprocess.call([DIR + "/bin/longestfasta"]+ command)
	elif code == "CBS":
		subprocess.call([DIR + "/bin/coreCBS"]+ command)




